package org.netbeans.modules.thymeleafcodecompletion.wizard;

import javax.swing.JPanel;
import org.openide.WizardDescriptor;

public final class ThymeleafVisualPanel1 extends JPanel {

    public ThymeleafVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lDialect = new javax.swing.JLabel();
        cbDialect = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(lDialect, org.openide.util.NbBundle.getMessage(ThymeleafVisualPanel1.class, "ThymeleafVisualPanel1.lDialect.text")); // NOI18N

        cbDialect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HTML5 with data-* attributes", "HTML5 with th:* attributes", "XHTML" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDialect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDialect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDialect)
                    .addComponent(cbDialect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDialect;
    private javax.swing.JLabel lDialect;
    // End of variables declaration//GEN-END:variables

    void read(WizardDescriptor wiz) {
        cbDialect.setSelectedIndex((int) wiz.getProperty(ThymeleafWizardIterator.WIZ_DIALECT));
    }

    void store(WizardDescriptor wiz) {
        wiz.putProperty(ThymeleafWizardIterator.WIZ_DIALECT, cbDialect.getSelectedIndex());
    }
}
