package org.netbeans.modules.thymeleafcodecompletion;

import java.util.HashMap;

/**
 * Thymeleaf attributes and documentation
 *
 * @author Artur Wiśniewski
 *
 */
public class ThymeleaData {

    /**
     * Array of Thymeleaf attributes.
     */
    private static String[] thymeleafAttributes = {
       // "#{}",
       // "${}",
        "xmlns:th=\"http://www.thymeleaf.org\"",
        "xmlns=\"http://www.w3.org/1999/xhtml\"",
        "xmlns:sec=\"http://www.thymeleaf.org/thymeleaf-extras-springsecurity3\"",
        "xmlns:sec=\"http://www.thymeleaf.org/thymeleaf-extras-springsecurity4\"",
        "th:alt-title",
        "th:attr",
        "th:attrappend",
        "th:attrprepend",
        "th:abbr",
        "th:accept",
        "th:accept-charset",
        "th:accesskey",
        "th:action",
        "th:align",
        "th:alt",
        "th:archive",
        "th:assert",
        "th:async",
        "th:audio",
        "th:autocomplete",
        "th:autofocus",
        "th:autoplay",
        "th:axis",
        "th:background",
        "th:bgcolor",
        "th:block",
        "th:border",
        "th:case",
        "th:cellpadding",
        "th:cellspacing",
        "th:challenge",
        "th:charset",
        "th:checked",
        "th:cite",
        "th:class",
        "th:classappend",
        "th:classid",
        "th:codebase",
        "th:codetype",
        "th:controls",
        "th:cols",
        "th:colspan",
        "th:compact",
        "th:content",
        "th:contenteditable",
        "th:contextmenu",
        "th:data",
        "th:datetime",
        "th:declare",
        "th:default",
        "th:defer",
        "th:dir",
        "th:disabled",
        "th:draggable",
        "th:dropzone",
        "th:each",
        "th:enctype",
        "th:for",
        "th:form",
        "th:formaction",
        "th:formenctype",
        "th:formmethod",
        "th:formnovalidate",
        "th:formtarget",
        "th:fragment",
        "th:frame",
        "th:frameborder",
        "th:headers",
        "th:height",
        "th:hidden",
        "th:high",
        "th:href",
        "th:hreflang",
        "th:hspace",
        "th:http-equiv",
        "th:icon",
        "th:id",
        "th:if",
        "th:include",
        "th:inline",
        "th:insert",
        "th:ismap",
        "th:keytype",
        "th:kind",
        "th:label",
        "th:lang",
        "th:lang-xmllang",
        "th:list",
        "th:longdesc",
        "th:loop",
        "th:low",
        "th:manifest",
        "th:marginheight",
        "th:marginwidth",
        "th:max",
        "th:maxlength",
        "th:media",
        "th:method",
        "th:min",
        "th:multiple",
        "th:name",
        "th:novalidate",
        "th:nowarp",
        "th:object",
        "th:onabort",
        "th:onafterprint",
        "th:onbeforeprint",
        "th:onbeforeunload",
        "th:onblur",
        "th:oncanplay",
        "th:oncanplaythrough",
        "th:onchange",
        "th:onclick",
        "th:oncontextmenu",
        "th:ondblclick",
        "th:ondrag",
        "th:ondragend",
        "th:ondragenter",
        "th:ondragleave",
        "th:ondragover",
        "th:ondragstart",
        "th:ondrop",
        "th:ondurationchange",
        "th:onemptied",
        "th:onended",
        "th:onerror",
        "th:onfocus",
        "th:onformchange",
        "th:onforminput",
        "th:onhashchange",
        "th:oninput",
        "th:oninvalid",
        "th:onkeydown",
        "th:onkeypress",
        "th:onkeyup",
        "th:onload",
        "th:onloadeddata",
        "th:onloadedmetadata",
        "th:onloadstart",
        "th:onmessage",
        "th:onmousedown",
        "th:onmousemove",
        "th:onmouseout",
        "th:onmouseover",
        "th:onmouseup",
        "th:onmousewheel",
        "th:onoffline",
        "th:ononline",
        "th:onpause",
        "th:onplay",
        "th:onplaying",
        "th:onpopstate",
        "th:onprogress",
        "th:onratechange",
        "th:onreadystatechange",
        "th:onredo",
        "th:onreset",
        "th:onresize",
        "th:onscroll",
        "th:onseeked",
        "th:onseeking",
        "th:onselect",
        "th:onshow",
        "th:onstalled",
        "th:onstorage",
        "th:onsubmit",
        "th:onsuspend",
        "th:ontimeupdate",
        "th:onundo",
        "th:onunload",
        "th:onvolumechange",
        "th:onwaiting",
        "th:open",
        "th:optimum",
        "th:pattern",
        "th:placeholder",
        "th:poster",
        "th:preload",
        "th:pubdate",
        "th:radiogroup",
        "th:readonly",
        "th:rel",
        "th:remove",
        "th:replace",
        "th:required",
        "th:rev",
        "th:reversed",
        "th:rows",
        "th:rowspan",
        "th:rules",
        "th:sandbox",
        "th:scheme",
        "th:scope",
        "th:scoped",
        "th:scrolling",
        "th:seamless",
        "th:selected",
        "th:size",
        "th:sizes",
        "th:span",
        "th:spellcheck",
        "th:src",
        "th:srclang",
        "th:standby",
        "th:start",
        "th:step",
        "th:style",
        "th:styleappend",
        "th:summary",
        "th:switch",
        "th:tabindex",
        "th:target",
        "th:text", // #{}
        "th:title",
        "th:type",
        "th:unless",
        "th:usemap",
        "th:utext",
        "th:value",
        "th:valuetype",
        "th:vspace",
        "th:width",
        "th:with",
        "th:wrap",
        "th:xmlbase",
        "th:xmllang",
        "th:xmlspace"

    };

    /**
     * Mapping doc to attributes
     */
    private static HashMap<String, String> docs = new HashMap<String, String>();

    static {
        docs.put("th:text", "text attribute");
        docs.put("th:test", "this is fake attribute.");
        docs.put("th:href", "Link");
    }

    ;

    /**
     *  Returns array containing Thymeleaf attributes.
     * @return String[] array of attributes.
     */
    public static String[] getThymeleafAttributes() {
        return thymeleafAttributes;
    }

    /**
     * Returns description for given Thymeleaf attribute.
     *
     * @param attribute for which we need documentation
     * @return String containing documentation description
     */
    public static String getDoc(String attribute) {
        return docs.get(attribute);
    }

}
